# Homework 1
## Neural Networks and Fuzzy Systems
### Exercise 1-2

Daniel Gonzalez - 12/02/2025

For start we load the proper libraries

In [2]:
# import modules
import numpy as np
import pandas as pd
import random

Then we load the DB that will be used for this exercise with the help of pandas as "pd"

In [3]:
df = pd.read_csv('NFL.csv')

We take the column "Age"

*   fillna will fill missing values
*   mode() calcules the mode from column, in the case that they were more than one then de [0] will take the first mode.
*   astype cast the result as int.

At last we print the data frame to ensure results are the expected.

In [4]:
df['Age'] = df['Age'].fillna(df['Age'].mode()[0]).astype(int)
df

,Age,Birth Place,Birthday,College,Current Status,Current Team,Experience,Height (inches),High School,High School Location,Name,Number,Player Id,Position,Weight (lbs),Years Played
0,27,"Grand Rapids , MI",5/23/1921,Notre Dame,Retired,NaN,3 Seasons,71.0,NaN,NaN,"Evans, Fred",NaN,fredevans/2513736,NaN,185.0,1946 - 1948
1,27,"Dayton , OH",12/21/1930,Dayton,Retired,NaN,1 Season,70.0,NaN,NaN,"Raiff, Jim",NaN,jimraiff/2523700,NaN,235.0,1954 - 1954
2,56,"Temple , TX",9/11/1960,Louisiana Tech,Retired,NaN,1 Season,74.0,NaN,NaN,"Fowler, Bobby",NaN,bobbyfowler/2514295,NaN,230.0,1985 - 1985
3,30,"New Orleans , LA",9/30/1986,LSU,Retired,NaN,5 Seasons,73.0,NaN,NaN,"Johnson, Quinn",NaN,quinnjohnson/79593,NaN,255.0,2009 - 2013
4,25,"Detroit , MI",3/31/1992,Central Michigan,Active,Pittsburgh Steelers,3rd season,77.0,Clintondale HS,"Clinton Twp.,Macomb Co., MI","Walton, L.T.",96.0,l.t.walton/2552444,DE,305.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17167,73,"Detroit , MI",2/15/1944,Michigan State,Retired,NaN,1 Season,71.0,NaN,NaN,"Goovert, Ron",NaN,rongoovert/2515082,NaN,225.0,1967 - 1967
17168,32,"Worland , WY",8/19/1984,Weber State,Retired,NaN,1 Season,75.0,NaN,NaN,"Folsom, J.D.",NaN,j.d.folsom/238485,NaN,230.0,2009 - 2010
17169,43,"Washington , DC",5/4/1974,Akron,Retired,NaN,1 Season,72.0,NaN,NaN,"Reader, Jamie",NaN,jamiereader/2502599,NaN,238.0,2001 - 2001
17170,27,"New Willard , TX",3/30/1921,Baylor,Retired,NaN,2 Seasons,73.0,NaN,NaN,"Barnett, Solon",NaN,solonbarnett/2509044,NaN,235.0,1945 - 1946
17171,54,"Bryan , TX",10/21/1962,Baylor,Retired,NaN,1 Season,73.0,NaN,NaN,"Johnson, Byron",NaN,byronjohnson/2517578,NaN,220.0,1987 - 1987

We split the Birthday in an array by "/" named "date" this will give us an array of 3 elements in order day, month, year.

In [5]:
date = df['Birthday'][3].split('/')
num = df['Age'][3]+int(date[2])

With avg we calculate the average age so we can estimate the current year when DB were collected.
With this data we can estimate a average year of birth.

In [6]:
avg = int(df['Age'].mean())
prom_y = int(num-avg)
prom_y

1976

Then as we only chose random day and moth

In [7]:
day = np.random.randint(1,30)
month = np.random.randint(1,12)
prom_bd = f'{day}/{month}/{prom_y}'
prom_bd

'23/6/1976'

Then we fill the NaN values in Birthday with this date

In [8]:
df['Birthday'] = df['Birthday'].fillna(prom_bd)
df

,Age,Birth Place,Birthday,College,Current Status,Current Team,Experience,Height (inches),High School,High School Location,Name,Number,Player Id,Position,Weight (lbs),Years Played
0,27,"Grand Rapids , MI",5/23/1921,Notre Dame,Retired,NaN,3 Seasons,71.0,NaN,NaN,"Evans, Fred",NaN,fredevans/2513736,NaN,185.0,1946 - 1948
1,27,"Dayton , OH",12/21/1930,Dayton,Retired,NaN,1 Season,70.0,NaN,NaN,"Raiff, Jim",NaN,jimraiff/2523700,NaN,235.0,1954 - 1954
2,56,"Temple , TX",9/11/1960,Louisiana Tech,Retired,NaN,1 Season,74.0,NaN,NaN,"Fowler, Bobby",NaN,bobbyfowler/2514295,NaN,230.0,1985 - 1985
3,30,"New Orleans , LA",9/30/1986,LSU,Retired,NaN,5 Seasons,73.0,NaN,NaN,"Johnson, Quinn",NaN,quinnjohnson/79593,NaN,255.0,2009 - 2013
4,25,"Detroit , MI",3/31/1992,Central Michigan,Active,Pittsburgh Steelers,3rd season,77.0,Clintondale HS,"Clinton Twp.,Macomb Co., MI","Walton, L.T.",96.0,l.t.walton/2552444,DE,305.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17167,73,"Detroit , MI",2/15/1944,Michigan State,Retired,NaN,1 Season,71.0,NaN,NaN,"Goovert, Ron",NaN,rongoovert/2515082,NaN,225.0,1967 - 1967
17168,32,"Worland , WY",8/19/1984,Weber State,Retired,NaN,1 Season,75.0,NaN,NaN,"Folsom, J.D.",NaN,j.d.folsom/238485,NaN,230.0,2009 - 2010
17169,43,"Washington , DC",5/4/1974,Akron,Retired,NaN,1 Season,72.0,NaN,NaN,"Reader, Jamie",NaN,jamiereader/2502599,NaN,238.0,2001 - 2001
17170,27,"New Willard , TX",3/30/1921,Baylor,Retired,NaN,2 Seasons,73.0,NaN,NaN,"Barnett, Solon",NaN,solonbarnett/2509044,NaN,235.0,1945 - 1946
17171,54,"Bryan , TX",10/21/1962,Baylor,Retired,NaN,1 Season,73.0,NaN,NaN,"Johnson, Byron",NaN,byronjohnson/2517578,NaN,220.0,1987 - 1987

For "College" as a calitative data we collect the unique values and added to a list named "coll_r".

Then with help from lambda function we chose a random value from our list and asigned to the missing values if the register is not NA/Missing then we left the content as it is.

In [9]:
coll_r = df['College'].unique().tolist()
df['College'] = df['College'].apply(lambda x: random.choice(coll_r) if pd.isna(x) else x)
df

,Age,Birth Place,Birthday,College,Current Status,Current Team,Experience,Height (inches),High School,High School Location,Name,Number,Player Id,Position,Weight (lbs),Years Played
0,27,"Grand Rapids , MI",5/23/1921,Notre Dame,Retired,NaN,3 Seasons,71.0,NaN,NaN,"Evans, Fred",NaN,fredevans/2513736,NaN,185.0,1946 - 1948
1,27,"Dayton , OH",12/21/1930,Dayton,Retired,NaN,1 Season,70.0,NaN,NaN,"Raiff, Jim",NaN,jimraiff/2523700,NaN,235.0,1954 - 1954
2,56,"Temple , TX",9/11/1960,Louisiana Tech,Retired,NaN,1 Season,74.0,NaN,NaN,"Fowler, Bobby",NaN,bobbyfowler/2514295,NaN,230.0,1985 - 1985
3,30,"New Orleans , LA",9/30/1986,LSU,Retired,NaN,5 Seasons,73.0,NaN,NaN,"Johnson, Quinn",NaN,quinnjohnson/79593,NaN,255.0,2009 - 2013
4,25,"Detroit , MI",3/31/1992,Central Michigan,Active,Pittsburgh Steelers,3rd season,77.0,Clintondale HS,"Clinton Twp.,Macomb Co., MI","Walton, L.T.",96.0,l.t.walton/2552444,DE,305.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17167,73,"Detroit , MI",2/15/1944,Michigan State,Retired,NaN,1 Season,71.0,NaN,NaN,"Goovert, Ron",NaN,rongoovert/2515082,NaN,225.0,1967 - 1967
17168,32,"Worland , WY",8/19/1984,Weber State,Retired,NaN,1 Season,75.0,NaN,NaN,"Folsom, J.D.",NaN,j.d.folsom/238485,NaN,230.0,2009 - 2010
17169,43,"Washington , DC",5/4/1974,Akron,Retired,NaN,1 Season,72.0,NaN,NaN,"Reader, Jamie",NaN,jamiereader/2502599,NaN,238.0,2001 - 2001
17170,27,"New Willard , TX",3/30/1921,Baylor,Retired,NaN,2 Seasons,73.0,NaN,NaN,"Barnett, Solon",NaN,solonbarnett/2509044,NaN,235.0,1945 - 1946
17171,54,"Bryan , TX",10/21/1962,Baylor,Retired,NaN,1 Season,73.0,NaN,NaN,"Johnson, Byron",NaN,byronjohnson/2517578,NaN,220.0,1987 - 1987

Here we estimate the mode and fill missing values with the most common result.

In [12]:
df['Current Status'] = df['Current Status'].fillna(df['Current Status'].mode()[0])
df['Current Team'] = df['Current Team'].fillna(df['Current Team'].mode()[0])
df['Experience'] = df['Experience'].fillna(df['Experience'].mode()[0])
df

,Age,Birth Place,Birthday,College,Current Status,Current Team,Experience,Height (inches),High School,High School Location,Name,Number,Player Id,Position,Weight (lbs),Years Played
0,27,"Grand Rapids , MI",5/23/1921,Notre Dame,Retired,Buffalo Bills,3 Seasons,71.0,NaN,NaN,"Evans, Fred",NaN,fredevans/2513736,NaN,185.0,1946 - 1948
1,27,"Dayton , OH",12/21/1930,Dayton,Retired,Buffalo Bills,1 Season,70.0,NaN,NaN,"Raiff, Jim",NaN,jimraiff/2523700,NaN,235.0,1954 - 1954
2,56,"Temple , TX",9/11/1960,Louisiana Tech,Retired,Buffalo Bills,1 Season,74.0,NaN,NaN,"Fowler, Bobby",NaN,bobbyfowler/2514295,NaN,230.0,1985 - 1985
3,30,"New Orleans , LA",9/30/1986,LSU,Retired,Buffalo Bills,5 Seasons,73.0,NaN,NaN,"Johnson, Quinn",NaN,quinnjohnson/79593,NaN,255.0,2009 - 2013
4,25,"Detroit , MI",3/31/1992,Central Michigan,Active,Pittsburgh Steelers,3rd season,77.0,Clintondale HS,"Clinton Twp.,Macomb Co., MI","Walton, L.T.",96.0,l.t.walton/2552444,DE,305.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17167,73,"Detroit , MI",2/15/1944,Michigan State,Retired,Buffalo Bills,1 Season,71.0,NaN,NaN,"Goovert, Ron",NaN,rongoovert/2515082,NaN,225.0,1967 - 1967
17168,32,"Worland , WY",8/19/1984,Weber State,Retired,Buffalo Bills,1 Season,75.0,NaN,NaN,"Folsom, J.D.",NaN,j.d.folsom/238485,NaN,230.0,2009 - 2010
17169,43,"Washington , DC",5/4/1974,Akron,Retired,Buffalo Bills,1 Season,72.0,NaN,NaN,"Reader, Jamie",NaN,jamiereader/2502599,NaN,238.0,2001 - 2001
17170,27,"New Willard , TX",3/30/1921,Baylor,Retired,Buffalo Bills,2 Seasons,73.0,NaN,NaN,"Barnett, Solon",NaN,solonbarnett/2509044,NaN,235.0,1945 - 1946
17171,54,"Bryan , TX",10/21/1962,Baylor,Retired,Buffalo Bills,1 Season,73.0,NaN,NaN,"Johnson, Byron",NaN,byronjohnson/2517578,NaN,220.0,1987 - 1987

Here we calculate the mean of the values that we already have, then we fill missing values with the one we calculate

In [13]:
Hw = int(df['Height (inches)'].mean())
df['Height (inches)'] = df['Height (inches)'].fillna(Hw)
df

,Age,Birth Place,Birthday,College,Current Status,Current Team,Experience,Height (inches),High School,High School Location,Name,Number,Player Id,Position,Weight (lbs),Years Played
0,27,"Grand Rapids , MI",5/23/1921,Notre Dame,Retired,Buffalo Bills,3 Seasons,71.0,NaN,NaN,"Evans, Fred",NaN,fredevans/2513736,NaN,185.0,1946 - 1948
1,27,"Dayton , OH",12/21/1930,Dayton,Retired,Buffalo Bills,1 Season,70.0,NaN,NaN,"Raiff, Jim",NaN,jimraiff/2523700,NaN,235.0,1954 - 1954
2,56,"Temple , TX",9/11/1960,Louisiana Tech,Retired,Buffalo Bills,1 Season,74.0,NaN,NaN,"Fowler, Bobby",NaN,bobbyfowler/2514295,NaN,230.0,1985 - 1985
3,30,"New Orleans , LA",9/30/1986,LSU,Retired,Buffalo Bills,5 Seasons,73.0,NaN,NaN,"Johnson, Quinn",NaN,quinnjohnson/79593,NaN,255.0,2009 - 2013
4,25,"Detroit , MI",3/31/1992,Central Michigan,Active,Pittsburgh Steelers,3rd season,77.0,Clintondale HS,"Clinton Twp.,Macomb Co., MI","Walton, L.T.",96.0,l.t.walton/2552444,DE,305.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17167,73,"Detroit , MI",2/15/1944,Michigan State,Retired,Buffalo Bills,1 Season,71.0,NaN,NaN,"Goovert, Ron",NaN,rongoovert/2515082,NaN,225.0,1967 - 1967
17168,32,"Worland , WY",8/19/1984,Weber State,Retired,Buffalo Bills,1 Season,75.0,NaN,NaN,"Folsom, J.D.",NaN,j.d.folsom/238485,NaN,230.0,2009 - 2010
17169,43,"Washington , DC",5/4/1974,Akron,Retired,Buffalo Bills,1 Season,72.0,NaN,NaN,"Reader, Jamie",NaN,jamiereader/2502599,NaN,238.0,2001 - 2001
17170,27,"New Willard , TX",3/30/1921,Baylor,Retired,Buffalo Bills,2 Seasons,73.0,NaN,NaN,"Barnett, Solon",NaN,solonbarnett/2509044,NaN,235.0,1945 - 1946
17171,54,"Bryan , TX",10/21/1962,Baylor,Retired,Buffalo Bills,1 Season,73.0,NaN,NaN,"Johnson, Byron",NaN,byronjohnson/2517578,NaN,220.0,1987 - 1987

High School is filled with the most common value from the ones we got that is "St. Thomas Aquinas HS"

In [15]:
HS_mode = df['High School'].mode()[0]
print(HS_mode)
df['High School'] = df['High School'].fillna(HS_mode)
df

St. Thomas Aquinas HS

,Age,Birth Place,Birthday,College,Current Status,Current Team,Experience,Height (inches),High School,High School Location,Name,Number,Player Id,Position,Weight (lbs),Years Played
0,27,"Grand Rapids , MI",5/23/1921,Notre Dame,Retired,Buffalo Bills,3 Seasons,71.0,St. Thomas Aquinas HS,NaN,"Evans, Fred",NaN,fredevans/2513736,NaN,185.0,1946 - 1948
1,27,"Dayton , OH",12/21/1930,Dayton,Retired,Buffalo Bills,1 Season,70.0,St. Thomas Aquinas HS,NaN,"Raiff, Jim",NaN,jimraiff/2523700,NaN,235.0,1954 - 1954
2,56,"Temple , TX",9/11/1960,Louisiana Tech,Retired,Buffalo Bills,1 Season,74.0,St. Thomas Aquinas HS,NaN,"Fowler, Bobby",NaN,bobbyfowler/2514295,NaN,230.0,1985 - 1985
3,30,"New Orleans , LA",9/30/1986,LSU,Retired,Buffalo Bills,5 Seasons,73.0,St. Thomas Aquinas HS,NaN,"Johnson, Quinn",NaN,quinnjohnson/79593,NaN,255.0,2009 - 2013
4,25,"Detroit , MI",3/31/1992,Central Michigan,Active,Pittsburgh Steelers,3rd season,77.0,Clintondale HS,"Clinton Twp.,Macomb Co., MI","Walton, L.T.",96.0,l.t.walton/2552444,DE,305.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17167,73,"Detroit , MI",2/15/1944,Michigan State,Retired,Buffalo Bills,1 Season,71.0,St. Thomas Aquinas HS,NaN,"Goovert, Ron",NaN,rongoovert/2515082,NaN,225.0,1967 - 1967
17168,32,"Worland , WY",8/19/1984,Weber State,Retired,Buffalo Bills,1 Season,75.0,St. Thomas Aquinas HS,NaN,"Folsom, J.D.",NaN,j.d.folsom/238485,NaN,230.0,2009 - 2010
17169,43,"Washington , DC",5/4/1974,Akron,Retired,Buffalo Bills,1 Season,72.0,St. Thomas Aquinas HS,NaN,"Reader, Jamie",NaN,jamiereader/2502599,NaN,238.0,2001 - 2001
17170,27,"New Willard , TX",3/30/1921,Baylor,Retired,Buffalo Bills,2 Seasons,73.0,St. Thomas Aquinas HS,NaN,"Barnett, Solon",NaN,solonbarnett/2509044,NaN,235.0,1945 - 1946
17171,54,"Bryan , TX",10/21/1962,Baylor,Retired,Buffalo Bills,1 Season,73.0,St. Thomas Aquinas HS,NaN,"Johnson, Byron",NaN,byronjohnson/2517578,NaN,220.0,1987 - 1987

For "High School Location" we face a litte issue as we cant simply check for most common result as this cant be random.

So we check from past column we fill if "St. Thomas Aquinas HS" was assigned then we asign the proper location that is "Fort Lauderdale, FL".

In [16]:
df.loc[df['High School'] == 'St. Thomas Aquinas HS', 'High School Location'] = 'Fort Lauderdale, FL'
df

,Age,Birth Place,Birthday,College,Current Status,Current Team,Experience,Height (inches),High School,High School Location,Name,Number,Player Id,Position,Weight (lbs),Years Played
0,27,"Grand Rapids , MI",5/23/1921,Notre Dame,Retired,Buffalo Bills,3 Seasons,71.0,St. Thomas Aquinas HS,"Fort Lauderdale, FL","Evans, Fred",NaN,fredevans/2513736,NaN,185.0,1946 - 1948
1,27,"Dayton , OH",12/21/1930,Dayton,Retired,Buffalo Bills,1 Season,70.0,St. Thomas Aquinas HS,"Fort Lauderdale, FL","Raiff, Jim",NaN,jimraiff/2523700,NaN,235.0,1954 - 1954
2,56,"Temple , TX",9/11/1960,Louisiana Tech,Retired,Buffalo Bills,1 Season,74.0,St. Thomas Aquinas HS,"Fort Lauderdale, FL","Fowler, Bobby",NaN,bobbyfowler/2514295,NaN,230.0,1985 - 1985
3,30,"New Orleans , LA",9/30/1986,LSU,Retired,Buffalo Bills,5 Seasons,73.0,St. Thomas Aquinas HS,"Fort Lauderdale, FL","Johnson, Quinn",NaN,quinnjohnson/79593,NaN,255.0,2009 - 2013
4,25,"Detroit , MI",3/31/1992,Central Michigan,Active,Pittsburgh Steelers,3rd season,77.0,Clintondale HS,"Clinton Twp.,Macomb Co., MI","Walton, L.T.",96.0,l.t.walton/2552444,DE,305.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17167,73,"Detroit , MI",2/15/1944,Michigan State,Retired,Buffalo Bills,1 Season,71.0,St. Thomas Aquinas HS,"Fort Lauderdale, FL","Goovert, Ron",NaN,rongoovert/2515082,NaN,225.0,1967 - 1967
17168,32,"Worland , WY",8/19/1984,Weber State,Retired,Buffalo Bills,1 Season,75.0,St. Thomas Aquinas HS,"Fort Lauderdale, FL","Folsom, J.D.",NaN,j.d.folsom/238485,NaN,230.0,2009 - 2010
17169,43,"Washington , DC",5/4/1974,Akron,Retired,Buffalo Bills,1 Season,72.0,St. Thomas Aquinas HS,"Fort Lauderdale, FL","Reader, Jamie",NaN,jamiereader/2502599,NaN,238.0,2001 - 2001
17170,27,"New Willard , TX",3/30/1921,Baylor,Retired,Buffalo Bills,2 Seasons,73.0,St. Thomas Aquinas HS,"Fort Lauderdale, FL","Barnett, Solon",NaN,solonbarnett/2509044,NaN,235.0,1945 - 1946
17171,54,"Bryan , TX",10/21/1962,Baylor,Retired,Buffalo Bills,1 Season,73.0,St. Thomas Aquinas HS,"Fort Lauderdale, FL","Johnson, Byron",NaN,byronjohnson/2517578,NaN,220.0,1987 - 1987

For the rest of the columns we estimate the most common value and fill the missing values. The only special case is number that we cast as int.

In [19]:
df['Name'] = df['Name'].fillna(df['Name'].mode()[0])
df['Number'] = df['Number'].fillna(df['Number'].mode()[0]).astype(int)
df['Player Id'] = df['Player Id'].fillna(df['Player Id'].mode()[0])
df['Position'] = df['Position'].fillna(df['Position'].mode()[0])
df['Weight (lbs)'] = df['Weight (lbs)'].fillna(df['Weight (lbs)'].mode()[0])
df['Years Played'] = df['Years Played'].fillna(df['Years Played'].mode()[0])
df

,Age,Birth Place,Birthday,College,Current Status,Current Team,Experience,Height (inches),High School,High School Location,Name,Number,Player Id,Position,Weight (lbs),Years Played
0,27,"Grand Rapids , MI",5/23/1921,Notre Dame,Retired,Buffalo Bills,3 Seasons,71.0,St. Thomas Aquinas HS,"Fort Lauderdale, FL","Evans, Fred",91,fredevans/2513736,WR,185.0,1946 - 1948
1,27,"Dayton , OH",12/21/1930,Dayton,Retired,Buffalo Bills,1 Season,70.0,St. Thomas Aquinas HS,"Fort Lauderdale, FL","Raiff, Jim",91,jimraiff/2523700,WR,235.0,1954 - 1954
2,56,"Temple , TX",9/11/1960,Louisiana Tech,Retired,Buffalo Bills,1 Season,74.0,St. Thomas Aquinas HS,"Fort Lauderdale, FL","Fowler, Bobby",91,bobbyfowler/2514295,WR,230.0,1985 - 1985
3,30,"New Orleans , LA",9/30/1986,LSU,Retired,Buffalo Bills,5 Seasons,73.0,St. Thomas Aquinas HS,"Fort Lauderdale, FL","Johnson, Quinn",91,quinnjohnson/79593,WR,255.0,2009 - 2013
4,25,"Detroit , MI",3/31/1992,Central Michigan,Active,Pittsburgh Steelers,3rd season,77.0,Clintondale HS,"Clinton Twp.,Macomb Co., MI","Walton, L.T.",96,l.t.walton/2552444,DE,305.0,1987 - 1987
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17167,73,"Detroit , MI",2/15/1944,Michigan State,Retired,Buffalo Bills,1 Season,71.0,St. Thomas Aquinas HS,"Fort Lauderdale, FL","Goovert, Ron",91,rongoovert/2515082,WR,225.0,1967 - 1967
17168,32,"Worland , WY",8/19/1984,Weber State,Retired,Buffalo Bills,1 Season,75.0,St. Thomas Aquinas HS,"Fort Lauderdale, FL","Folsom, J.D.",91,j.d.folsom/238485,WR,230.0,2009 - 2010
17169,43,"Washington , DC",5/4/1974,Akron,Retired,Buffalo Bills,1 Season,72.0,St. Thomas Aquinas HS,"Fort Lauderdale, FL","Reader, Jamie",91,jamiereader/2502599,WR,238.0,2001 - 2001
17170,27,"New Willard , TX",3/30/1921,Baylor,Retired,Buffalo Bills,2 Seasons,73.0,St. Thomas Aquinas HS,"Fort Lauderdale, FL","Barnett, Solon",91,solonbarnett/2509044,WR,235.0,1945 - 1946
17171,54,"Bryan , TX",10/21/1962,Baylor,Retired,Buffalo Bills,1 Season,73.0,St. Thomas Aquinas HS,"Fort Lauderdale, FL","Johnson, Byron",91,byronjohnson/2517578,WR,220.0,1987 - 1987